include $(TOPDIR)/rules.mk
LUCI_TITLE:=LuCI support for Netwatch
LUCI_DEPENDS:=+luci-base +rpcd-mod-luci +netwatch
LUCI_PKGARCH:=all
PKG_LICENSE:=GPL-2.0-only
include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
